from typing import Any, Protocol


class FileStorageProtocol(Protocol):
    def save(self, key: Any, data: bytes) -> str: ...
    def load(self, key: Any) -> bytes: ...
    def delete(self, key: Any) -> bool: ...
    def exists(self, key: Any) -> bool: ...
    def list(self) -> list[Any]: ...
