name: Deploy to Stage

on:
  pull_request:
    branches:
      - stage
  workflow_dispatch: # Enables manual triggering of the workflow

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'stage' && github.head_ref != 'main'
        run: |
          echo "ERROR: You can only merge to stage from main."
          exit 1

  # deploy_aws:
  #   needs: build-and-push-image
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: read
  #   steps:
  #     - name: Create SSH key
  #       run: |
  #         mkdir -p ~/.ssh/
  #         echo "$SSH_PRIVATE_KEY" | tr -d '\r' > key.pem
  #         chmod 600 key.pem
  #       shell: bash
  #       env:
  #         SSH_PRIVATE_KEY: ${{secrets.SSH_MY}}
  #     - name: Deploy to AWS
  #       run: |
  #         ssh -i key.pem  -o strictHostKeyChecking=accept-new ${{ env.SERVER }} "
  #         docker login ${{ env.REGISTRY }} -u username -p ${{ secrets.GITHUB_TOKEN }} &&
  #         docker pull ${{ env.IMAGE }} &&
  #         docker tag ${{ env.IMAGE }} testpage &&
  #         docker rmi ${{ env.IMAGE }} &&
  #         docker rm -f my-app || true &&
  #         docker run -d --name my-app -p 80:8000 testpage
  #         "
  #       shell: bash
  #       env:
  #         SERVER: ${{ secrets.AWS_USER }}@${{ secrets.AWS_IP }}
  #         IMAGE: ${{ env.REGISTRY }}/${{ github.actor }}/testpage:main
