name: Create Image

on:
  workflow_dispatch:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    if: ${{ false }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - 
        name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64, linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy_aws:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > awskey.pem
          chmod 600 awskey.pem
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_MY}}
      - name: Deploy to AWS
        run: |
          ssh -i awskey.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_IP }} "
          docker login ${{ env.REGISTRY }} -u username -p ${{ secrets.GITHUB_TOKEN }} &&
          docker pull ${{ env.REGISTRY }}/${{ github.actor }}/testpage:main &&
          docker rm -f my-app || true &&
          docker run -d --name my-app -p 80:8000 ${{ env.REGISTRY }}/${{ github.actor }}/testpage:main
          "
        # ssh -i ../private.key ubuntu@${{ secrets.AWS_IP }} "docker pull ghcr.io/username/repo:latest"
        # ssh -i ../private.key ubuntu@${{ secrets.AWS_IP }} "docker run -d -p 80:80 ghcr.io/username/repo:latest"
        shell: bash
    #     docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com &&
    #     docker pull $DOCKER_IMAGE &&
    #     docker rm -f my-app || true &&
    #     docker run -d --name my-app -p 80:8000 $DOCKER_IMAGE
    #   "