name: Python Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Enables manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=testpage --cov-report=xml --cov-report=term

      - name: Generate coverage badge
        run: |
          pip install coverage-badge
          coverage-badge -o coverage.svg

      - name: Commit and push badge
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update coverage badge"
          file_pattern: "coverage.svg"
