name: Python Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Enables manual triggering of the workflow

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint and format Python code with ruff
      run: |
       # Lint with the default set of ruff rules with GitHub Annotations
       ruff check --format=github --target-version=py312
       # Verify the code is properly formatted
       ruff format --diff --target-version=py312
    - name: Test with pytest
      run: |
        pytest
